mode: standalone

rootUser: minio
rootPassword: minio123

replicas: 1

persistence:
  enabled: true
  size: 2Gi
  storageClass: gp3-csi

resources:
  requests:
    memory: 512Mi
    cpu: 250m

buckets:
  - name: loki-chunks
  - name: loki-ruler
  - name: loki-admin